
[ env ]
TERM = "xterm-256color"

[window]

opacity = 1
blur = true
decorations = "Buttonless"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.50

[general]
import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
