
[ env ]
TERM = "xterm-256color"

[window]

opacity = 0.8
blur = true
decorations = "Buttonless"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.50

[general]
import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
]
